title: Tiago Tamagusko
author: Tiago Tamagusko
email: tamagusko@gmail.com
url: https://tamagusko.com
baseurl: ""
description: >
  Postdoc · AI, Computer Vision & Data Science
permalink: /:slug.html

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
