services:
  jekyll:
    image: ruby:3.3-slim
    volumes:
      - .:/site
      - jekyll:/usr/local/bundle
    ports:
      - '4000:4000'
    working_dir: /site
    command: >
      bash -c "
        apt-get update -qq && apt-get install -y -qq build-essential git > /dev/null 2>&1 &&
        bundle install --quiet &&
        bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000 --baseurl /preview
      "

volumes:
  jekyll:
